; 開発用設定 (元 Dockerfile の display_errors = On 相当)
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

date.timezone = Asia/Tokyo

upload_max_filesize = 32M
post_max_size = 32M
